### ISSUE TITLE
[입문] 1주차(Chapter 1) > 발표1: 1p~18p

### ISSUE THREAD

**Issue by madplay** [NMP-Study/spark2023#1]

**Comment by madplay** [comment]
# 스파크의 시작

**Comment by madplay** [comment]
# Chapter 1. 아파치 스파크 소개: 통합 분석 엔진
## 스파크의 시작
### 빅데이터 처리의 한계
- 전통적인 저장 시스템(RDBMS) 등으로는 구글의 대량의 문서를 탐색하고 색인하는데 한계가 있었다.
  - 자연스럽게 구글 파일 시스템(Google File System), 맵리듀스(MapReduce), 빅테이블(BigTable) 등이 등장하게 된 계기가 됨
- 이 결과물들은 하둡 파일 시스템(HDFS), 맵리듀스의 구현에도 이바지하였고 이들은 향후 하둡 프레임워크에 포함되었다.

### 스파크의 등장
- 하지만 하둡의 운영 복잡도, 불편한 API 사용 등의 어려움이 있었다. → 스파크라는 프로젝트가 시작한 계기
- 2014년 5월 아파치 스파크 1.0 릴리즈

## 스파크의 특성: 스파크의 설계 철학
### 속도
- **CPU와 메모리 성능의 향상 → 스파크의 내부 구현도 발전**
  - 효과적인 멀티스레딩과 병렬처리를 지원하는 유닉스 기반 OS가 포함되있으며, 스파크는 이러한 모든 요소에서 이득을 얻을 수 있다.
- **질의 연산을 방향성 비순환 그래프(Directed Acyclic Graph)로 구성**
  - DAG의 스케줄러와 질의 최적화 모듈은 효율적인 연산 그래프를 만들어서 각각의 태스크로 분해하여 클러스터의 워커 노드 위에서 병렬 수행될 수 있도록 한다.
- **물리적 실행 엔진: 텅스텐(Tungsten)**
  - 텅스텐은 전체적 코드 생성(Whole-stage code generation)이라는 기법을 사용하여 실행을 위한 간결한 코드를 생성한다.
- **인메모리 방식**
  - 모든 중간 결과는 메모리에 유지되며, 디스크 I/O를 제한적으로 사용하므로 성능이 크게 향상된다.
 
### 사용 편리성
- 유연한 분산 데이터세트(Resilient Distributed DataSet, RDD)라고 불리는 단순하고 핵심적인 논리 자료구조 구축
- 연산의 종류로 트랜스포메이션(Transformation)과 액션(Action)의 집함과 단순한 프로그래밍 모델을 제공함

### 모듈성
- 스칼라, 자바, 파이썬 등 다양한 언어를 지원한다.
- 스파크 SQL, 스티리밍, MLlib, GraphX 등 하나의 엔진 안에서 연동된 상태로 사용 가능한 라이브러리 제공

### 확장성
- 저장보다는 빠른 병렬 연산 엔진에 초점이 맞추어져 있음

**Comment by mbyul** [comment]
# Chapter 1. 아파치 스파크 소개: 통합 분석 엔진

## 스파크의 시작

- RDBMS 같은 전통적인 저장 시스템이 아닌 새로운 접근 방식의 필요성
  - 구글 파일 시스템(GFS), 맵리듀스(MR), 빅테이블(BigTable) 등장
- 하둡 파일 시스템(HDFS)와 맵리듀스 구현으로 하둡 프레임웍의 일부가 됨
- 하둡의 단점
  - 번거로운 운영 복잡도
  - 맵리듀스 API는 장황하고 많은 양의 기본 셋업 코드 필요
  - 많은 MR 태스크가 필요해지면서 중간 과정 데이터를 로컬 디스크에 써야함
  - 머신러닝이나 스트리밍, 상호 반응하는 SQL 계통의 질의 등 다른워크로드와 연계가 한계가 있음
- 위에 문제점을 보완하기 위해 <b>`스파크Spark`</b> 라는 프로젝트가 시작 됨

## 아파치 스파크란?

- 데이터 센터나 클라우드에서 대규모 분산 데이터 처리를 하기 위해 설계된 통합형 엔진
- 스파크의 설계 철학
  - 속도
    - 성능이 향상된 수많은 코어, 멀티스레딩과 병렬처리 지원하는 유닉스 기반 OS에 최적화
    - 질의 연산을 `방향성 비순환 그래프(DAG)` 로 구성, 각각의 태스크로 분해하여 클러스터의 워커노드 위에서 병렬 수행 가능하도록 해줌
    - 텅스텐(물리적 실행 엔진)은 전체적 코드 생성 기법으로 간결한 코드를 생성
    - 모든 중간 결과는 <b> 메모리에 유지</b>되며 디스크 I/O를 제한적으로 사용
  - 사용 편리성
    - 연산의 종류로 트랜스포메이션과 액션의 집합과 단순한 프로그래밍 모델을 제공. 사용자가 편한 언어로 사용 가능 
  - 모듈성
    - 다양한 타입의 워크로드에 적용 가능
    - 문서화 잘 된 API들로 이루어진 통합 라이브러리를 제공 ( 스파크SQL, 스파크 정형화 스트리밍, 스파크 MLlib, GraphX)
  - 확장성
    - 수많은 데이터 소스에서 데이터를 읽어 메모리에서 처리가 가능

### 단일화된 스택으로의 아파치 컴포넌트

- 각각의 컴포넌트는 스파크의 중심 장애 대응 엔진과 별도로 존재
  - 어느 언어로 사용해서 정형화 API를 사용하더라도 실제 코드는 고도로 경량화된 바이트코드로 변환되어 클러스터 전체에 나뉘어 워커 노드의 JVM에서 실행 된다.
- 스파크SQL
- 스파크MLlib
- 스파크 정형화 스트리밍
- GraphX

## 아파치 스파크의 분산 실행

- 스파크 어플리케이션은 스파크 클러스터의 병렬 작업들을 조율하는 하나의 드라이버 프로그램으로 이루어짐
- 드라이버는 SparkSession 객체를 통해 클러스터의 분산 컴포넌트들에 접근함 

### 스파크 드라이버

- SparkSession 객체를 초기화 하는 책임을 가진 스파크 애플리케이션의 일부
- 클러스터 매니저와 통신하며 스파크 이그제큐터들을 위해 자원 요청
- 모든 스파크 작업을 DAG 연산 형태로 변환 및 스케쥴링
- 각 실행 단위를 태스크로 나누어 스파크 이그제큐터들에게 분배

### SparkSession

- 모든 스파크 연산과 데이터에 대한 통합 연결 채널
- 모든 스파크 기능을 한 군데에서 접근할 수 있는 시작점을 제공

### 클러스터 매니저

- 클러스터에서 자원을 관리 및 할당하는 책임을 가짐

### 스파크 이그제큐터

- 스파크 이그제큐터는 클러스터의 각 워커 노드에서 동작
- 워커에서 태스크를 실행하는 역할을 함
- 배포모드에서 노드당 하나의 이그제큐터만 실행

### 배포모드

- 스파가 여러 다른 환경에서 다른 설정으로 돌아갈 수 있도록 다양한 배포 모드를 지원.

### 분산 데이터와 파티션

- 실제 물리적인 데이터는 HDFS나 클라우드 저장소에 존재하는 파티션이 되어 저장소 전체에 분산됨
- 스파크 이그제큐터는 가급적 네트워크에서 가장 가까운 파티션을 읽어 들이도록 태스크를 할당

<img width="600" src="https://github.com/NMP-Study/spark2023/assets/13082749/fcc9cb02-a932-456e-9390-5b17ea6dd851"/>

**Comment by madplay** [comment]
Q) DAG, MapReduce 등등은 일단 스킵하고 넘어가도 되는가?
Q) 스파크 세션이라는 것은 ?
Q) 클러스터는 애플리케이션의 묶음이라고 말할 수 있는가?

**Comment by jeongwon-p** [comment]
### QNA
1. 맵리듀스, DAG, 하둡 같은것을 미리 알아야하는가?
 -아니다. 뒤에 가서 필요할때 알아도 된다.
 -참고로 DAG는 비순환 그래프 알고리즘 개념이고 airflow에서 쓰이는 DAG랑 개념은 같지만 airflow 만의 DAG 이론이 따로 있으니 airflow 보실때 보면 좋을 듯 합니다.
2. spark.stop() 를 명시적으로 사용하는지?
 -spark 어플리케이션이 종료되면 자동으로 stop 되서 명시적으로 사용한 적은 없다.

**Comment by madplay** [comment]
6/7 완료
