### ISSUE TITLE
[입문] 2주차(Chapter 2) > 발표2: 19p ~ 42p

### ISSUE THREAD

**Issue by madplay** [NMP-Study/spark2023#2]
- 아파치 스파크 다운로드 내용 제외 가능
- < 3단계: 스파크 애플리케이션 개념의 이해 > 부터 시작

**Comment by madplay** [comment]
# Chapter 2. 아파치 스파크 다운로드 및 시작

**Comment by luckyDaveKim** [comment]
# Chapter 2. 아파치 스파크 다운로드 및 시작

## 스파크 앱 개념 이해

### 앱
- API를 써서 스파크 위에서 돌아가는 사용자 프로그램
- 드라이버 프로그램과 클러스터의 실행기로 이뤄짐

### SparkSession
- 스파크 코어 기능들과 상호 작용할 수 있는 진입점 제공하며 해당 API로 프로그래밍 할 수 있도록 해주는 객체
- 스카트 쉘에서 스파크 드라이버는 기본적으로 SparkSession을 제공하지만, 스파크 앱에서는 사용자가 SparkSession 객체를 생성해서 써야 함

### 잡(job)
- 스파크 액션(save, collect)에 대한 응답으로 생성되는 여러 태스크로 이루어진 병렬 연산
- 스파크 쉘로 작업 동안, 드라이버는 스파크 앱을 하나 이상의 스파크 잡으로 변환하며, 각 잡은 DAG로 변환 됨
- 스파크의 실행 계획이 되며, DAG 그래프에서 각각의 노드는 하나 이상의 스파크 스테이지에 해당 됨

### 태스트(task)
- 스파크 이그제큐터로 보내지는 작업의 가장 기본 단위
- 각 태스크는 개별 CPU 코어에 할당되며, 데이터의 개별 파티션을 갖고 작업함

### 스테이지(stage)
- 잡의 태스크 중 서로 의존성을 가지는 태스크 모음
- 어떤 작업이 연속적으로 또는 병렬적으로 수행되는지에 맞춰 스테이지에 해당하는 DAG 노드가 생성됨

## 트랜스포메이션, 액션, 지연평가
스파크 연산은 트랜스포메이션과 액션으로 구분

### 트랜스포메이션
- 불변성 특징을 가진 원본 ㅇ데이터를 수정하지 않고 하나의 스파크 데이터 프레임을 새로운 데이터 프레임으로 변형함
  - 즉, select, filter 같은 ㅇ녀산은 원본 데이터 프레임을 수정하지 않으며, 새로운 데이터 프레임을 생성해서 반환
- 모든 트랜스포메이션은 뒤늦게 평가됨
  - 즉, 결과는 즉시 계산되지 않으며 계보(lineage)라 불리는 형태로 기록
  - 기록된 리니지는 실행 계획의 후반에서 스파크가 확실한 트랜스포메이션들끼리 재배열하거나 합쳐서 최적화
- 리니지와 데이터 불변성은 장애에 대한 데이터 내구성 제공
  - 스파크는 리니지에 각 트랜스포메이션을 기록해놓고, 데이터 프레임은 트랜스포메이션을 거치는 동안 불변하기 때문에 단순히 기록된 리니지를 재실행하는 것만으로도 원래 상태를 다시 만들어낼 수 있음
- 종류
  - orderBy()
  - groupBy()
  - filter()
  - select()
  - join()

### 액션
- 하나의 액션은 모든 기록된 트랜스포메이션의 지연 연산을 발동
- 종류
  - show()
  - take()
  - count()
  - collect()
  - save()

### 지연 평가
- 연계된 트랜스포메이션을 살펴보며 쿼리 최적화 가능

```python
strings = spark.read.text("../README.md")
filtered = strings.filter(strings.value.contains("Spark"))

# 이 전까지는 아무것도 실제로 실행되지 않음
filtered.count()
```

## 좁은/넓은 트랜스포메이션

### 좁은 트랜스포메이션
- 하나의 입력 파티션을 연산하여 하나의 결과 파티션을 내놓는 트랜스포메이션은 좁은 트랜스포메이션임
- 위 예의 filter(), contains()는 하나의 파티션을 처리하여 데이터 교환 없이 결과 파티션을 생성해 내므로 좁은 트랜스포메이션임

### 넓은 트랜스포메이션
- groupBy(), orderBy() 는 다른 파티션으로부터 데이터를 읽어 들여서 합치고 디스크에 쓰는 등의 일을 하기 때문에 넓은 트랜스포메이션임

### 스파크 UI
- 스파크는 GUI를 통한 스파크 앱을 볼 수 있게 해줌 (http://localhost:4040)
- 다양한 레벨(잡, 스테이지, 태스트 레벨)에서 확인 가능
- 확인 가능한 내용
  - 스케줄러의 스테이지와 태스트 목록
  - RDD 크기와 메모리 사용의 요약
  - 환경 정보
  - 실행 중인 이그제큐터 정보
  - 모든 스파크 SQL 쿼리

### 첫 번째 단독 앱 M&M 세기

예제 코드
```python
from __future__ import print_function

import sys

from pyspark.sql import SparkSession

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: mnmcount <file>", file=sys.stderr)
        sys.exit(-1)

    spark = (SparkSession
        .builder
        .appName("PythonMnMCount")
        .getOrCreate())
    # get the M&M data set file name
    mnm_file = sys.argv[1]
    # read the file into a Spark DataFrame
    mnm_df = (spark.read.format("csv")
        .option("header", "true")
        .option("inferSchema", "true")
        .load(mnm_file))
    mnm_df.show(n=5, truncate=False)

    # aggregate count of all colors and groupBy state and color
    # orderBy descending order
    count_mnm_df = (mnm_df.select("State", "Color", "Count")
                    .groupBy("State", "Color")
                    .sum("Count")
                    .orderBy("sum(Count)", ascending=False))

    # show all the resulting aggregation for all the dates and colors
    count_mnm_df.show(n=60, truncate=False)
    print("Total Rows = %d" % (count_mnm_df.count()))

    # find the aggregate count for California by filtering
    ca_count_mnm_df = (mnm_df.select("*")
                       .where(mnm_df.State == 'CA')
                       .groupBy("State", "Color")
                       .sum("Count")
                       .orderBy("sum(Count)", ascending=False))

    # show the resulting aggregation for California
    ca_count_mnm_df.show(n=10, truncate=False)
```

결과
```text
+-----+------+-----+
|State|Color |Count|
+-----+------+-----+
|TX   |Red   |20   |
|NV   |Blue  |66   |
|CO   |Blue  |79   |
|OR   |Blue  |71   |
|WA   |Yellow|93   |
+-----+------+-----+
only showing top 5 rows

+-----+------+----------+
|State|Color |sum(Count)|
+-----+------+----------+
|CA   |Yellow|100956    |
|WA   |Green |96486     |
|CA   |Brown |95762     |
|TX   |Green |95753     |
|TX   |Red   |95404     |
|CO   |Yellow|95038     |
|NM   |Red   |94699     |
|OR   |Orange|94514     |
|WY   |Green |94339     |
|NV   |Orange|93929     |
|TX   |Yellow|93819     |
|CO   |Green |93724     |
|CO   |Brown |93692     |
|CA   |Green |93505     |
|NM   |Brown |93447     |
|CO   |Blue  |93412     |
|WA   |Red   |93332     |
|WA   |Brown |93082     |
|WA   |Yellow|92920     |
|NM   |Yellow|92747     |
|NV   |Brown |92478     |
|TX   |Orange|92315     |
|AZ   |Brown |92287     |
|AZ   |Green |91882     |
|WY   |Red   |91768     |
|AZ   |Orange|91684     |
|CA   |Red   |91527     |
|WA   |Orange|91521     |
|NV   |Yellow|91390     |
|UT   |Orange|91341     |
|NV   |Green |91331     |
|NM   |Orange|91251     |
|NM   |Green |91160     |
|WY   |Blue  |91002     |
|UT   |Red   |90995     |
|CO   |Orange|90971     |
|AZ   |Yellow|90946     |
|TX   |Brown |90736     |
|OR   |Blue  |90526     |
|CA   |Orange|90311     |
|OR   |Red   |90286     |
|NM   |Blue  |90150     |
|AZ   |Red   |90042     |
|NV   |Blue  |90003     |
|UT   |Blue  |89977     |
|AZ   |Blue  |89971     |
|WA   |Blue  |89886     |
|OR   |Green |89578     |
|CO   |Red   |89465     |
|NV   |Red   |89346     |
|UT   |Yellow|89264     |
|OR   |Brown |89136     |
|CA   |Blue  |89123     |
|UT   |Brown |88973     |
|TX   |Blue  |88466     |
|UT   |Green |88392     |
|OR   |Yellow|88129     |
|WY   |Orange|87956     |
|WY   |Yellow|87800     |
|WY   |Brown |86110     |
+-----+------+----------+

Total Rows = 60
+-----+------+----------+
|State|Color |sum(Count)|
+-----+------+----------+
|CA   |Yellow|100956    |
|CA   |Brown |95762     |
|CA   |Green |93505     |
|CA   |Red   |91527     |
|CA   |Orange|90311     |
|CA   |Blue  |89123     |
+-----+------+----------+
```

**Comment by mbyul** [comment]
# Chapter 2. 아파치 스파크 다운로드 및 시작

## 스파크 애플리케이션 개념의 이해

### 애플리케이션 

- API를 써서 스파크 위에서 돌아가는 사용자 프로그램
- 드라이버 프로그램과 클러스터의 실행기로 이루어짐

### SparkSession

- 코어 기능들과 상호 작용할 수 있는 진입점을 제공하며 그 API로 프로그래밍 할 수 있게 해주는 객체
- 스파크 애플리케이션은 사용자가 SparkSession 객체를 생성해서 사용

### 잡(job)

- 스파크 액션에 응답으로 생성되는 여러 태스크로 이루어진 병렬 연산

### 스테이지(stage)

- 각 잡은 스테이지라 불리는 서로 의존성을 가지는 다수의 태스크 모음

### 태스크(task)

- 스파크 이그제큐터로 보내지는 작업 실행의 가장 기본적인 단위

## 트랜스포메이션, 액션, 지연 평가

- 스파크 연산은 트랜스포메이션과 액션으로 구분

### 트랜스포메이션

- 불변성의 특징을 가진 원본 데이터를 수정하지 않고 하나의 스파크 데이터 프레임을 새로운 프레임으로 변형
   - select()나 filter() 같은 연산은 원본 데이터 프레임을 수정하지 않으며, 대신 새로운 데이터 프레임으로 연산 결과를 만들어 되돌려 준다.
- 결과가 즉시 계산되는게 아니라 계보라 불리는 형태로 기록

### 액션

- 하나의 액션은 모든 기록된 트랜스포메이션의 지연 연산을 발동시킴

### 지연 평가

- 스파크가 사용자의 연계된 트랜스포메이션들을 살펴봄으로서 쿼리 최적화를 가능하게 함
- 아래 예제에서는 filtered.count()가 입력되기 전까지 아무것도 셸에서 실제로 실행되지 않음

``` python
strings = spark.read.text("../README.md")
filtered = strings.filter(strings.value.contains("Spark"))
filtered.count()
``` 

## 좁은/넓은 트랜스포메이션

### 좁은 트랜스포메이션

- 하나의 입력 파티션을 연산하여 하나의 결과 파티션을 내놓는 트랜스포메이션은 어느 것이든 좁은 트랜스포메이션
- 앞의 예제에서 filter()와 contains()는 하나의 파티션을 처리하여 데이터 교환 없이 결과 파티션을 생성함

### 넓은 트랜스포메이션

- groupBy()나 orderBy()
- 다른 파티션으로부터 데이터를 읽어 들여서 합치고 디스크에 쓰는 등의 일을 함

## 스파크UI

- 스케쥴러의 스테이지와 태스크 목록
- RDD 크기와 메모리 사용의 요약
- 환경 정보
- 실행중인 이그제큐터 정보
- 모든 스파크 SQL 쿼리

**Comment by madplay** [comment]
### Q) DAG, MapReduce 등등은 일단 스킵하고 넘어가도 되는가?
### Q) 스파크 세션이라는 것은 ?
### Q) 클러스터는 애플리케이션의 묶음이라고 말할 수 있는가?

**Comment by madplay** [comment]
6/14 완료
