### ISSUE TITLE
마지막 회차 스터디를 앞두고 미리 준비하는 회고

### ISSUE THREAD

**Issue by madplay** [NMP-Study/spark2023#35]
>  간단하고 자유롭게 스터디는 어땠는지, 다음 스터디 주제, 스터디 방식 등등!
> 마지막 회차 스터디 전에 각자 한 번 남겨보시져~

**Comment by madplay** [comment]
### 스터디 소감
- 팀원 모두가 와닿는 스터디는 아니어서 아쉬웠다.
- 물론 흥미를 갖고 심화 과정까지 참여해주신 분들도 많으셨지만, 실무에 적용할 수 있는 사람은 데이터파트 인원뿐이었던 것 같다. (그래도 모두 긍정적으로 말씀해주셔서 감사드림... 🙏 )

### 다음 스터디, 이건 어때요?
- 자바 11 ~ 21의 신규 기능 JEP 명세서를 한 명씩 맡아서 읽고 해석하기
  - 전체가 부담이라면 주요 코드 변경사항 정도?
- 소프트웨어 아키텍처 설계에 대한 공부
- 새로 나온 스프링 부트 새 버전을 준비

**Comment by KimYunsang-v** [comment]
### 스터디 소감 

- 스파크 관련 부족하던 이론을 짚고 넘어갈 수 있어서 좋았다.

### 다음 스터디 

#### webflux 
- webflux API 사용법이 아닌 webflux 내부 구조, 로직 등을 파악해보고싶습니다.
- ex. 어떻게 이벤트가 발행되어 Subscriber로 전해지며, 어떻게 비동기 논블록킹으로 작동하는지...
> 아직 webflux를 제대로 몰라서 가독성을 버리고 사이드이펙트 발생 위험까지 감수하며 사용해야하는지 잘 모르겠습니다 ㅎ

**Comment by madplay** [comment]
OSS / todo로 이동~
