### ISSUE TITLE
[입문] 4주차(Chapter 3-2) > 발표4: 71p ~ 85p

### ISSUE THREAD

**Issue by madplay** [NMP-Study/spark2023#4]
- < 데이터세트 API > 부터 시작

**Comment by RulLu16** [comment]
## 데이터세트 API

**Comment by okhee** [comment]
### 이 장에서 알아볼 것
- DataSet의 특성과 DataFrame과의 차이점
- 스파크 SQL과 이를 뒷받침하는 엔진

# Spark Dataset API


# Spark SQL and the Underlying Engine
### 스파크 SQL
  - 스키마, 구조가 명시된 Structured data (Parquet, Avro) 에 SQL 같은 질의를 직접 수행할 수 있음
  - 스파크 컴포넌트를 통합하고 여러 개발 언어의 DataFrame/Dataset API 위의 추상화를 제공해 데이터 작업 단순화
  - (중략)
  - 최종 실행을 위한 최적화된 query plans와 JVM을 위한 최적화 코드 생성 (feat. Catalyst Optimizer & Project Tungsten)

### The Catalyst Optimizer

**Comment by qlqhqo2341** [comment]
# 데이터세트 API
- 데이터프레임/데이터세트 API를 유사한 인터페이스를 갖도록 정형화 API로 일원화 함.
- 개념적으로 데이터프레임은 `Dataset[Row]`의 다른 이름
  - Row는 서로 다른 타입의 값을 저장할 수 있는 포괄적 JVM 객체
- 반면 데이터세트는 스칼라에서 엄격하게 타입이 정해진 JVM 객체의 집합

## 정적 타입 객체, 동적 타입 객체, 포괄적인 Row
- 파이썬과 R의 경우 데이터 세트 API를 사용할 수 없음.
    - 컴파일시 타입안전이 보장되지 않아서 타입이 실행시에 정해지기 때문
- 역으로 자바와 스칼라는 타입안전이 보장되므로, 컴파일 타임에 타입을 정할 수 있음.

| 언어      | 정적/동적 타입 기본 추상화객체                | 타입여부                           |
| --------- | --------------------------------------------- | ---------------------------------- |
| 스칼라    | `Dataset[T]` 와 `DataFrame`(`Dataset[Row]`의 타입 alias) | 양쪽 모두 가능                     |
| 자바      | `Dataset<T>`                                    | 정적 타입                          |
| 파이썬, R | `DataFrame`                                     | 포괄적 Row 객체를 사용한 동적 타입 |

- Row 객체는 배열처럼 인덱스를 사용해 접근할 수 있으며 다양한 타입의 값을 담을 수 있음
    - https://github.com/NMP-Study/spark2023/issues/3 (표 3-2, 3-3)
- getter류 함수가 제공됨.
```python
# Row 객체 파이썬으로 핸들링 하기
# https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.Row.html

from pyspark.sql import Row
row = Row(350, True, "Learning spark 2E", None)

print(row[0])
print(row[1])
print(row[2])
```

```
350
True
Learning spark 2E
```

```scala
// Row 객체 스칼라로 핸들링 하기
// https://spark.apache.org/docs/3.1.3/api/scala/org/apache/spark/sql/Row.html

import org.apache.spark.sql.Row
val row = Row(350, true, "Learning spark 2E", null)

println(row.getInt(0))
println(row.getBoolean(1))
println(row.getString(2))
```

```
350
true
Learning spark 2E
```
- 반면에 정적 객체는 JVM에서 실제 자바 클래스나 스칼라 클래스가 된다.
  => 데이터 세트의 아이템은 곧바로 하나의 JVM의 객체가 되어 접근할 수 있다.
    - 개념적으로 `Dataset[String]` 이나 `List<String>` 이나 String 객체의 모음이라는 점에는 차이가 없음.

## 데이터 세트 생성
- 데이터 세트를 만들때에도 스키마를 알아야 한다.
    - 추론이 가능하나 비용이 필요하다.
- 스칼라의 케이스 클래스나 자바의 자바빈 클래스를 사용 가능함.

### 스칼라 케이스 클래스
- Iot json 파일들을 읽어보자
```scala
// 케이스 클래스로 읽기
// 다음 paragphrah에서 진행해야 정상 실행됨

// json 데이터의 포맷을 위해 케이스 클래스를 정의함.
case class DeviceIoTData (battery_level: Long, c02_level: Long, cca2: String, cca3: String, cn: String, device_id: Long, device_name: String, humidity: Long, ip: String, latitude: String, lcd: String, longitude: Double, scale: String, temp: Long, timestamp: Long)

// 케이스 클래스로 읽기2
// 데이터를 읽어서 Dataset[Row]를 Dataset[DeviceIoTDevice]
val ds = spark.read
    .json("study2023/book_sample/databricks-datasets/iot-devices/iot_devices.json")
    .as[DeviceIoTData]
    
ds.show(5, false)
```
```
+-------------+---------+----+----+-------------+---------+---------------------+--------+-------------+--------+------+---------+-------+----+-------------+ |battery_level|c02_level|cca2|cca3|cn |device_id|device_name |humidity|ip |latitude|lcd |longitude|scale |temp|timestamp | +-------------+---------+----+----+-------------+---------+---------------------+--------+-------------+--------+------+---------+-------+----+-------------+ |8 |868 |US |USA |United States|1 |meter-gauge-1xbYRYcj |51 |68.161.225.1 |38.0 |green |-97.0 |Celsius|34 |1458444054093| |7 |1473 |NO |NOR |Norway |2 |sensor-pad-2n2Pea |70 |213.161.254.1|62.47 |red |6.15 |Celsius|11 |1458444054119| |2 |1556 |IT |ITA |Italy |3 |device-mac-36TWSKiT |44 |88.36.5.1 |42.83 |red |12.83 |Celsius|19 |1458444054120| |6 |1080 |US |USA |United States|4 |sensor-pad-4mzWkz |32 |66.39.173.154|44.06 |yellow|-121.32 |Celsius|28 |1458444054121| |4 |931 |PH |PHL |Philippines |5 |therm-stick-5gimpUrBB|62 |203.82.41.9 |14.58 |green |120.97 |Celsius|25 |1458444054122| +-------------+---------+----+----+-------------+---------+---------------------+--------+-------------+--------+------+---------+-------+----+-------------+ only showing top 5 rows

ds: org.apache.spark.sql.Dataset[DeviceIoTData] = [battery_level: bigint, c02_level: bigint ... 13 more fields]

```


## 데이터 세트에서 가능한 작업들
- 데이터프레임에서 했던 작업들을 데이터 세트에서도 해보자.
```scala

val filterTempDS = ds.filter(d => d.temp > 30 && d.humidity > 70)
filterTempDS.show(5, false)
```
- 데이터세트의 함수인 filter의 인자로 다시 함수를 넣어주었다
    - filter의 시그니처: `filter(func: (T) > Boolean): DataSet[T]`
    - 람다 함수의 인풋으로 Dataset의 제너릭이 활용되어, `DeviceIoTData` JVM객체가 그대로 들어온다!

```scala
// 데이터세트에서 할 수 있는 작업들

// filter
val filterTempDS = ds.filter(d => d.temp > 30 && d.humidity > 70)
filterTempDS.show(5, false)

// 클래스 바꿔보기
val dsTemp = ds
    .filter { d => d.temp > 25 }
    .map { d => (d.temp, d.device_name, d.device_id, d.cca3) }
    .toDF("temp", "device_name", "device_id", "cca3")
    .as[DeviceTempByCountry]
dsTemp.show(5, false)

//첫 번째 데이터만 가져와보기
val device = dsTemp.first()
println(device)

// 클래스 바꿔보기 다른 방법
val dsTemp2 = ds
    .select($"temp", $"device_name", $"device_id", $"cca3")
    .where("temp > 25")
    .as[DeviceTempByCountry]
dsTemp2.show(5, false)
```

# 데이터 프레임 VS 데이터 세트
- 데이터프레임 or 데이터 세트가 적합
    - 스파크에게 **어떻게** 해야하는지보다 **무엇을** 해야하는지만 알려주고 싶으면
    - 풍부한 표현, 높은 수준의 추상화 및 DSL 연산을 원한다면
    - 높은 수준의 표현력, 필터, 맵, 집계 연산들, SQL질의가 필요한 경우
    - 칼럼 지향접근, 반정형화된 데이터에 대한 관계형 연산이 필요한 경우
- 데이터 세트가 적합
    - 컴파일 타임에 엄격한 체크를 원하는 경우 (여러개의 케이스 클래스 생성에 부담이 없다면)
    - 인코더를 써서 프로젝트 텅스텐의 직렬화를 통한 이득을 보고싶다면
- 데이터 프레임이 적합
    - SQL과 유사한 질의를 쓰는 관계형 변환이 필요하다면
    - 일원화, 코드 최적화 스파크 컴포넌트들 사이에서의 API 단순화를 원한다면
    - 공간/속도의 효율성을 원한다면
- 컴파일 오류를 더 잘 잡고 싶다면 아래 오류가 발견되는 시점을 참고

| -         | SQL       | 데이터프레임 | 데이터세트  |
| --------- | --------- | ------------ | ----------- |
| 문법 오류 | 실행 시점 | 컴파일 시점  | 컴파일 시점 |
| 분석 오류 | 실행 시점 | 실행 시점    | 컴파일 시점 |

## 언제 RDD를 사용하는가
- 아래 시나리오에서 고려해서 사용함
    - 데이터프레임과 데이터세트에서 얻을 수 있는 코드최적화, 효과적인 공간 사용, 퍼포먼스의 이득을 포기할 수 있다.
    - 스파크가 **어떻게** 질의를 수행할지 정확하게 지정해주고 싶다.
- `df.rdd` 만 호출하면 rdd로 바뀌어 사용할 수 있음 (변환 비용이 있어 지양해야함.)

# 스파크 SQL과 하부 엔진
- 스파크 SQL 엔진이 하는 일들
    - 스파크 컴포넌트 들을 통합하고 데이터프레임/데이터세트가 스칼라, 파이썬 R 등으로 정형화 데이터 관련 작업을 단순화 할 수 있도록 추상화 해준다.
    - 아파치 하이브 메타스토어와 테이블에 접근한다.
    - 정형화된 파일 포맷(json, csv 등등)에서 스키마와 정형화 데이터를 읽고 쓰며 데이터를 임시 테이블로 변환한다.
    - 빠른 데이터 탐색을 할 수 있도록 대화형 스파크 sql 쉘을 제공한다.
    - 표준 jdbc/odbc 커넥터를 통해 외부의 도구들과 연결할 수 있는 중간 다리 역할
    - 최종 실행을 위해 최적화된 질의 계획과 JVM을 위한 최적화된 코드를 생성한다.
 
## 카탈리스트 옵티마이저
- 연산 쿼리를 받아서 실행 계획을 변환함

### 네 단계의 쿼리 최적화 과정
1. 분석
    - 추상 문법 트리를 생성함.
    - 칼럼, 데이터 타입, 함수, 테이블, 데이터베이스 이름 등이 모두 Catalog 객체에 담겨있으며 접근이 가능함.
2.  논리적 최적화
    - 표준 규칙을 기반으로 최적화 접근방식을 사용해 여러 계획을 수립후
    - 비용 기반 옵티마이저로 각 계획에 비용을 책정하여 선택함
3. 물리 계획 수립
    - 선택된 논리적 계획을 기반으로 물리적 연산자로 바꿈
4. 코드 생성
    - 각 머신에서 최종적으로 실행할 바이트 코드를 생성함. (컴파일러 처럼 동작함)
    - 프로젝트 텅스텐이 이 역할을 하게됨.

**Comment by madplay** [comment]
7/12 완료
